import Head from 'next/head';

// Components
import Layout from '@/Layouts/Layout';
import { EventBanner } from '@/components/Organisms/EventBanner/EventBanner';
import { EventSummary } from '@/components/Molecules/EventSummary/EventSummary';
import { EventDescription } from '@/components/Molecules/EventDescription/EventDescription';
import { PerformancesSoldOut } from '@/components/Molecules/PerformancesPlaceholder/PerformancesSoldOut';
import { RefundPolicyCard } from '@/components/Molecules/RefundPolicyCard/RefundPolicyCard';
import { AvailableStockCard } from '@/components/Molecules/AvailableStockCard/AvailableStockCard';
import { VenueCard } from '@/components/Molecules/VenueCard/VenueCard';
import { Heading } from '@/components/Atoms/Heading/Heading';

export default function EventPage() {
  return (
    <>
      <Head>
        <title>Event Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <EventBanner />
        <div className="mx-auto container my-10 lg:my-20">
          <div className="grid grid-cols-1 md:grid-cols-8 gap-4">
            <div className="col-span-1 md:col-span-4 lg:col-span-4 space-y-6">
              <EventSummary />
              <EventDescription
                title="Description"
                description="<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod nunc sit amet aliquam lacinia, nunc nisl aliquet nisl, nec aliquam nisl nisl sit amet lorem. Sed euismod nunc sit amet aliquam lacinia, nunc nisl aliquet nisl, nec aliquam nisl nisl sit amet lorem.</p>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod nunc sit amet aliquam lacinia, nunc nisl aliquet nisl, nec aliquam nisl nisl sit amet lorem. Sed euismod nunc sit amet aliquam lacinia, nunc nisl aliquet nisl, nec aliquam nisl nisl sit amet lorem.</p>"
              />
            </div>
            <div className="col-span-1 md:col-span-4 lg:col-start-6 lg:col-span-3">
              <div className="grid grid-cols-2 gap-4">
                <ul className="col-span-2 bg-gray-200">
                  <VenueCard />
                </ul>
                <div className="col-span-1">
                  <AvailableStockCard />
                </div>
                <div className="col-span-1">
                  <AvailableStockCard />
                </div>
                <div className="col-span-2">
                  <RefundPolicyCard />
                </div>
              </div>
            </div>
            <div className="col-span-1 md:col-span-8">
              <Heading level="h3" className="mb-4">
                Performances
              </Heading>
              <PerformancesSoldOut />
            </div>
          </div>
        </div>
      </Layout>
    </>
  );
}
