import Head from 'next/head';

// Components
import Layout from '@/Layouts/Layout';
import { Heading } from '@/components/Atoms/Heading/Heading';
import { BackButton } from '@/components/Atoms/BackButton/BackButton';
import Image from 'next/image';
import { SupportDetails } from '@/components/Molecules/SupportDetails/SupportDetails';
import Cta from '@/components/Atoms/Cta/Cta';
import { WhatsOnFilters } from '@/components/Molecules/WhatsOnFilters/WhatsOnFilters';
import { EventCardHorizontal } from '@/components/Molecules/EventCardHorizontal/EventCardHorizontal';
import { EventCardList } from '@/components/Organisms/EventCardList/EventCardList';
import { useState } from 'react';
import { Icon } from '@/components/Atoms/Icons/DemoIcons';

export default function VenuePage() {
  const [view, setView] = useState<'list' | 'calendar'>('list');
  return (
    <>
      <Head>
        <title>Event Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="mx-auto container">
          <div className="grid grid-cols-2 gap-8">
            <div className="col-span-2 relative">
              <BackButton className="text-indigo-700" text="Venues" />
            </div>
            <div className="col-span-2 md:col-span-1">
              <Image
                src="https://picsum.photos/1024/780/"
                alt=""
                width={1024}
                height={780}
              />
            </div>
            <div className="col-span-2 md:col-span-1">
              <SupportDetails />
              <Cta href="#" text="Get directions" className="mb-4" />
              <ul className="space-y-4">
                <li className="flex items-center gap-2">
                  <span className="min-w-9 h-9 rounded-full bg-gray-100 text-gray-500 inline-flex justify-center items-center">
                    <Icon name="Orientation" width="20" height="20" />
                  </span>
                  <span>Orientation / Familiarisation Visits</span>
                </li>
                <li className="flex items-center gap-2">
                  <span className="min-w-9 h-9 rounded-full bg-gray-100 text-gray-500 inline-flex justify-center items-center">
                    <Icon name="Toilet" width="20" height="20" />
                  </span>
                  <span>Accessible Toilets</span>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div className="mx-auto container my-10 lg:my-20">
          <div className="grid grid-cols-1">
            <div className="col-span-1">
              <Heading level="h3" className="text-indigo-700">
                <span className="inline-block border-b-2 border-b-current">
                  What&apos;s on
                </span>
              </Heading>
              <WhatsOnFilters
                view="list"
                setView={() =>
                  setView(view === 'calendar' ? 'list' : 'calendar')
                }
              />
              {view === 'calendar' ? (
                <div className="container mx-auto my-10 lg:my-20">
                  <div className="grid grid-cols-1 lg:grid-cols-2 gap-4 items-center justify-between">
                    {Array.from({ length: 6 }).map((_, i) => (
                      <EventCardHorizontal
                        key={i.toString()}
                        className="col-span-1"
                      />
                    ))}
                  </div>
                </div>
              ) : (
                <EventCardList />
              )}
            </div>
          </div>
        </div>
      </Layout>
    </>
  );
}
